# 指定本yml依赖docker-compose的哪个版本制定的
version: '3.3'
# 服务容器
services:
  # Nginx容器配置
  nginx:
    # 使用镜像文件
    image: nginx:latest
    # 映射端口
    ports:
      - 80:80
    # 链接到php-fpm
    links:
      - php7.3
    # 需要挂载的目录
    volumes:
      # Nginx虚拟主机配置文件
      - D:\docker-compose\nginx\conf.d:/etc/nginx/conf.d
      # Nginx配置文件
      - D:\docker-compose\nginx\nginx.conf:/etc/nginx/nginx.conf
      # Nginx日志文件
      - D:\docker-compose\nginx\logs:/var/log/nginx
      # 项目目录
      - D:\docker-compose\www:/var/www
    # 设置依赖关系
    depends_on:
      - php7.3

  # MySQL容器配置
  mysql5.7:
    # 使用镜像文件
    image: mysql:5.7
    # 端口映射
    ports:
      - 3306:3306
    # 设置MySQL的root用户密码
    environment:
      - MYSQL_ROOT_PASSWORD=root
    # 挂载文件
    volumes:
      # 挂载MySQL存储文件
      - D:\docker-compose\mysql\mysql-data:/var/lib/mysql
      # 需要手动开启日志文件记录
      # 笔记地址：http://note.youdao.com/noteshare?id=90d92b0bc877584c78b6c32d9aa93605&sub=01FA3A13A3A9427EA223A0F87ACFD414
      # 挂载MySQL日志文件
      - D:\docker-compose\mysql\log:/var/log/mysql

  # PHP容器配置
  php7.3:
    # 使用镜像文件
    image: php7.3:1.0
    # 挂载文件
    volumes:
      - D:\docker-compose\www:/var/www
    # 暴露的端口
    expose:
      - "9000"
    # 设置依赖关系
    depends_on:
      - mysql5.7